allgray: 0
arch: vit_large_patch16_384
aug: true
aug_ver: 19
batch_size: 56
best_valid_score: 0.0
ckpt: ../10141300_v3_1_other_0927newbatch_withvalid/logs/exman-train.py/runs/000002/checkpoint_best.pth.tar
color_dist_s: 1.0
config_file: params.yaml
data: imagenet
dataset_ver: 5
dist: ddp
dist_address: 127.0.0.1:1234
eval_freq: 17
eval_only: false
gpu: 0
im_size: 384
iters: 250200
log_freq: 100
lr: 1.0e-05
lr_schedule: const
multiplier: 2
name: imagenet-reproduce
node_rank: 0
number_of_processes: 8
opt: adam
problem: sim-clr
reference: 0
root: /siim/code_1014/descriptor_track/10141300_v3_1_other_0927newbatch_queryref_withvalid/logs/exman-train.py/runs/000001
save_freq: 100
scale_lower: 0.25
seed: -1
sim_pt_start: 35000
sync_bn: true
temperature: 0.1
tmp: false
valid_size: 2500
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1

time: '2021-10-18T16:49:51'
id: 1
