allgray: 0
arch: vit_large_patch16_224
aug: true
aug_ver: 19
batch_size: 256
best_valid_score: 0.0
ckpt: ../v3_1/logs/exman-train.py/runs/000002/checkpoint_best.pth.tar
color_dist_s: 1.0
config_file: ../v3_1/logs/exman-train.py/runs/000002/params.yaml
data: imagenet
dataset_ver: 5
dist: ddp
dist_address: 127.0.0.1:1234
eval_freq: 17
eval_only: false
gpu: 0
im_size: 224
iters: 250200
log_freq: 100
lr: 1.0e-05
lr_schedule: const
multiplier: 2
name: imagenet-reproduce
node_rank: 0
number_of_processes: 8
opt: adam
problem: sim-clr
reference: 0
root: /shopee/queryref_finetune_1005_2/logs/exman-train.py/runs/000023
save_freq: 100
scale_lower: 0.25
seed: 1
sim_pt_start: 200000
sync_bn: true
temperature: 0.1
tmp: false
valid_size: 2500
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1

time: '2021-10-05T19:54:47'
id: 23
