allgray: 0
arch: vit_large_patch16_224
aug: true
aug_ver: 18
batch_size: 24
best_valid_score: 0.0
best_valid_score_merge5: 0.0
ckpt: /shopee3/matching-10072221-color/logs/exman-train.py/runs/000001/checkpoint_best_merge5.pth.tar
color_dist_s: 1.0
config_file: params3.yaml
data: imagenet
dataset_ver: 6
dist: ddp
dist_address: 127.0.0.1:1234
eval_freq: 500
eval_only: false
gpu: 0
im_size: 224
iters: 250200
log_freq: 100
lr: 1.0e-05
lr_schedule: const
multiplier: 2
name: imagenet-reproduce
node_rank: 0
number_of_processes: 8
opt: adam
problem: sim-clr
reference: 0
root: /shopee3/matching-1009-from-1008-from-1001-nochange/logs/exman-train.py/runs/000004
save_freq: 100
scale_lower: 0.25
seed: 842
sim_pt_start: 440000
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1

time: '2021-10-11T12:32:22'
id: 4
