arch: vit_large_patch16_224
aug: true
aug_ver : 17
dataset_ver : 5
allgray : 1
batch_size: 256
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: ddp
dist_address: '127.0.0.1:1234'
eval_freq: 500
gpu: 0
iters: 250200
log_freq: 100
lr: 1e-5
lr_schedule: const
multiplier: 2
name: imagenet-reproduce
node_rank: 0
opt: adam
problem: sim-clr
root: ''
save_freq: 100
scale_lower: 0.25
seed: 1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
