arch: vit_small
aug: true
aug_ver : 6
allgray : 1
batch_size: 1536
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: ddp
dist_address: '127.0.0.1:1234'
eval_freq: 100
gpu: 0
iters: 250200
log_freq: 100
lr: 1e-6
lr_schedule: const
multiplier: 2
name: imagenet-reproduce
node_rank: 0
opt: adam
problem: sim-clr
root: ''
save_freq: 1000
scale_lower: 0.25
seed: 1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
